### ISSUE TITLE
Compilation warnings with gcc 10

### ISSUE THREAD

**Issue by lmoneta** [VcDevel/Vc#253] opened 2020-05-11 08:33 UTC
Vc version / revision | Operating System | Compiler & Version | Compiler Flags | Assembler & Version | CPU
----------------------|------------------|--------------------|----------------|---------------------|----
       1.4.1               |        fedora32          |        gcc 10            |                |                     |

## Testcase
```cpp
```

## Actual Results

We are seeing these compiler warnings in ROOT when using gcc10 on Fedora 32, see 
for example: 

http://cdash.cern.ch/viewBuildError.php?type=1&buildid=870296

**Comment by Axel-Naumann** [comment] 2020-06-09 08:41
For completeness and in case cdash swallows logs:

```
In file included from /.../build/include/Vc/vector.h:32,
                 from /.../build/include/Vc/Vc:30,
                 from /.../root/test/testVc.cxx:32:
/.../build/include/Vc/scalar/vector.h: In member function ‘V2 Vc_1::Vector<T, Vc_1::VectorAbi::Scalar>::reinterpretCast() const’:

/.../build/include/Vc/scalar/vector.h:218:55: warning: ‘V2 Vc_1::Vector<T, Vc_1::VectorAbi::Scalar>::reinterpretCast() const’ is deprecated: use reinterpret_components_cast instead [-Wdeprecated-declarations]

  218 |             return V2(*reinterpret_cast<const AliasT2 *>(&m_data));
      |                                                       ^


/.../build/include/Vc/scalar/vector.h:215:13: note: declared here

  215 |             reinterpretCast() const
      |             ^~~~~~~~~~~~~~~
```

**Comment by linev** [comment] 2020-08-28 12:27
I guess, one can close issue

**Comment by agheata** [comment] 2020-09-01 15:12
The issue is resolved by removing the deprecated method

**Closed as completed by agheata** 2020-09-01 15:12 UTC
